name: flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  retrofit: ^4.0.1
  dio: ^5.2.0
  json_annotation: ^4.8.1
  injectable: ^2.1.2
  get_it: ^7.6.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  retrofit_generator: ^7.0.1
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.6


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProMedium.ttf
          weight: 500
